import { useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { apiRequest } from '@/api/http/mutator';
import { normaliseApiError } from '@/api/http/errors';
import { Button, Card, Field, FormErrorSummary, Input } from '@/components/ui';

function AuthFrame({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <main className="grid min-h-screen place-items-center bg-slate-100 p-4"><Card className="w-full max-w-md p-6 sm:p-8"><div className="mb-6 flex items-center gap-3"><span className="brand-mark" aria-hidden="true">S</span><div><h1 className="text-xl font-bold">{title}</h1><p className="mt-1 text-sm text-slate-600">{description}</p></div></div>{children}</Card></main>;
}

export function ForgotPasswordPage() {
  const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false); const [errors, setErrors] = useState<Record<string, string[]>>({});
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setErrors({}); try { await apiRequest({ url: '/auth/password/forgot', method: 'POST', data: { email } }); setSent(true); } catch (error) { const apiError = normaliseApiError(error); setErrors(Object.keys(apiError.fieldErrors).length ? apiError.fieldErrors : { form: [apiError.message] }); } finally { setBusy(false); } };
  return <AuthFrame title="Reset your password" description="We will send reset instructions if the account exists.">{sent ? <div className="ui-alert ui-alert--info">Check your inbox for the reset link.</div> : <><FormErrorSummary errors={errors}/><form onSubmit={submit} className="space-y-5"><Field label="Work email" error={errors.email?.[0]} required>{({ id }) => <Input id={id} type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} required/>}</Field><Button type="submit" busy={busy} className="w-full">Send reset link</Button></form></>}<Link className="mt-5 block text-center text-sm font-semibold text-blue-700" to="/login">Back to sign in</Link></AuthFrame>;
}

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const [email, setEmail] = useState(params.get('email') ?? ''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [busy, setBusy] = useState(false); const [errors, setErrors] = useState<Record<string, string[]>>({});
  const submit = async (event: FormEvent) => { event.preventDefault(); setErrors({}); if (password !== confirmation) { setErrors({ password_confirmation: ['Passwords do not match.'] }); return; } setBusy(true); try { await apiRequest({ url: '/auth/password/reset', method: 'POST', data: { email, password, password_confirmation: confirmation, token: params.get('token') ?? '' } }); navigate('/login', { replace: true }); } catch (error) { const apiError = normaliseApiError(error); setErrors(Object.keys(apiError.fieldErrors).length ? apiError.fieldErrors : { form: [apiError.message] }); } finally { setBusy(false); } };
  return <AuthFrame title="Choose a new password" description="Use a strong password unique to this account."><FormErrorSummary errors={errors}/><form onSubmit={submit} className="space-y-5"><Field label="Email" error={errors.email?.[0]} required>{({ id }) => <Input id={id} type="email" value={email} onChange={(e) => setEmail(e.target.value)} required/>}</Field><Field label="New password" error={errors.password?.[0]} required>{({ id }) => <Input id={id} type="password" minLength={12} autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} required/>}</Field><Field label="Confirm password" error={errors.password_confirmation?.[0]} required>{({ id }) => <Input id={id} type="password" autoComplete="new-password" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} required/>}</Field><Button type="submit" busy={busy} className="w-full">Reset password</Button></form></AuthFrame>;
}

export function InvitationAcceptancePage() {
  const { token = '' } = useParams(); const navigate = useNavigate(); const [name, setName] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [errors, setErrors] = useState<Record<string, string[]>>({});
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setErrors({}); try { await apiRequest({ url: `/invitations/${token}/accept`, method: 'POST', data: { token, name, password } }); navigate('/login', { replace: true }); } catch (error) { const apiError = normaliseApiError(error); setErrors(Object.keys(apiError.fieldErrors).length ? apiError.fieldErrors : { form: [apiError.message] }); } finally { setBusy(false); } };
  return <AuthFrame title="Accept your invitation" description="Set up your staff account to join Support CRM."><FormErrorSummary errors={errors}/><form onSubmit={submit} className="space-y-5"><Field label="Full name" error={errors.name?.[0]} required>{({ id }) => <Input id={id} autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} required/>}</Field><Field label="Password" hint="Use at least 12 characters." error={errors.password?.[0]} required>{({ id }) => <Input id={id} type="password" minLength={12} autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} required/>}</Field><Button type="submit" busy={busy} className="w-full">Create account</Button></form></AuthFrame>;
}
