import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { apiRequest } from '@/api/http/mutator';
import { ApiPage } from '@/api/http/envelope';
import { AsyncBoundary } from '@/shell/AsyncBoundary';
import { Button, Card, Field, FormErrorSummary, Input, PageHeader, Select, Textarea, useToast } from '@/components/ui';
import { KnowledgeLifecyclePanel } from '@/features/knowledge/KnowledgeLifecyclePanel';
import { KnowledgeRenderedPreview } from '@/features/knowledge/KnowledgeRenderedPreview';
import { pickBilingual } from '@/features/tickets/utils/bilingual';
import { DetailPageSkeleton, FormSkeleton } from '@/shell/states/LoadingState';

type Row = Record<string, unknown>;
type FormError = Error & { fieldErrors?: Record<string, string[]> };
const identifier = (data: Row) => String(data.uuid ?? data.id ?? '');

export function NewTicketPage() {
  const navigate = useNavigate(); const toast = useToast(); const { i18n } = useTranslation();
  const [form, setForm] = useState({ customer_uuid: '', department_uuid: '', priority: 'normal', subject: '', body: '' });
  const customers = useQuery({ queryKey: ['customers', 'options'], queryFn: () => apiRequest<ApiPage<Row>>({ url: '/customers', method: 'GET', params: { per_page: 100 } }) });
  const departments = useQuery({ queryKey: ['departments', 'options'], queryFn: () => apiRequest<ApiPage<Row>>({ url: '/departments', method: 'GET', params: { per_page: 100 } }) });
  const mutation = useMutation({ mutationFn: () => apiRequest<Row>({ url: '/tickets', method: 'POST', data: form, headers: { 'Idempotency-Key': crypto.randomUUID() } }), onSuccess: (data) => { toast.notify('Ticket created'); navigate(`/tickets/${identifier(data)}`); } });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <div><PageHeader title="Create ticket" description="Open a tracked support case for an existing customer."/><Card className="max-w-3xl p-6"><form className="grid gap-5" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}><FormErrorSummary errors={(mutation.error as FormError)?.fieldErrors ?? {}}/><div className="grid gap-5 sm:grid-cols-2"><Field label="Customer" required error={(mutation.error as FormError)?.fieldErrors?.customer_uuid?.[0]}>{({id,describedBy}) => <Select id={id} aria-describedby={describedBy} value={form.customer_uuid} onChange={(e) => update('customer_uuid', e.target.value)} required><option value="">Select customer</option>{customers.data?.items.map((row) => <option key={identifier(row)} value={identifier(row)}>{String(row.name ?? row.email ?? identifier(row))}</option>)}</Select>}</Field><Field label="Department" required error={(mutation.error as FormError)?.fieldErrors?.department_uuid?.[0]}>{({id,describedBy}) => <Select id={id} aria-describedby={describedBy} value={form.department_uuid} onChange={(e) => update('department_uuid', e.target.value)} required><option value="">Select department</option>{departments.data?.items.map((row) => <option key={identifier(row)} value={identifier(row)}>{pickBilingual(row.name as { ar?: string; en?: string } | string, i18n.language) || identifier(row)}</option>)}</Select>}</Field></div><Field label="Priority" required>{({id}) => <Select id={id} value={form.priority} onChange={(e) => update('priority', e.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></Select>}</Field><Field label="Subject" required>{({id}) => <Input id={id} value={form.subject} onChange={(e) => update('subject', e.target.value)} maxLength={255} required/>}</Field><Field label="Message" required>{({id}) => <Textarea id={id} rows={8} value={form.body} onChange={(e) => update('body', e.target.value)} required/>}</Field><div className="flex gap-3"><Button type="submit" busy={mutation.isPending}>Create ticket</Button><Button type="button" variant="secondary" onClick={() => navigate('/tickets')}>Cancel</Button></div></form></Card></div>;
}

export function NewCustomerPage() {
  const navigate = useNavigate(); const toast = useToast(); const [name, setName] = useState(''); const [locale, setLocale] = useState('en');
  const mutation = useMutation({ mutationFn: () => apiRequest<Row>({ url: '/customers', method: 'POST', data: { name, preferred_locale: locale }, headers: { 'Idempotency-Key': crypto.randomUUID() } }), onSuccess: (data) => { toast.notify('Customer created'); navigate(`/customers/${identifier(data)}`); } });
  return <div><PageHeader title="Create customer" description="Add a customer record before attaching contacts and support history."/><Card className="max-w-2xl p-6"><form className="grid gap-5" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}><FormErrorSummary errors={(mutation.error as FormError)?.fieldErrors ?? {}}/><Field label="Customer name" required>{({id}) => <Input id={id} value={name} onChange={(e) => setName(e.target.value)} maxLength={255} required/>}</Field><Field label="Preferred language">{({id}) => <Select id={id} value={locale} onChange={(e) => setLocale(e.target.value)}><option value="en">English</option><option value="ar">Arabic</option></Select>}</Field><div className="flex gap-3"><Button type="submit" busy={mutation.isPending}>Create customer</Button><Button type="button" variant="secondary" onClick={() => navigate('/customers')}>Cancel</Button></div></form></Card></div>;
}

function ArticleForm({ article }: { article?: Row }) {
  const navigate = useNavigate(); const toast = useToast(); const queryClient = useQueryClient(); const id = article ? identifier(article) : '';
  const sourceTitle = (article?.title ?? {}) as Record<string,string>; const sourceBody = (article?.body ?? {}) as Record<string,string>;
  const categories = useQuery({queryKey:['knowledge','categories'],queryFn:()=>apiRequest<Row[]>({url:'/knowledge/categories',method:'GET'})});
  const flatten = (rows:Row[]):Row[] => rows.flatMap((row)=>[row,...flatten(Array.isArray(row.children)?row.children as Row[]:[])]);
  const categoryOptions=flatten(categories.data??[]);
  const [form, setForm] = useState({ title_en: sourceTitle.en ?? '', title_ar: sourceTitle.ar ?? '', body_en: sourceBody.en ?? '', body_ar: sourceBody.ar ?? '', visibility: String(article?.visibility ?? 'internal'), knowledge_category_id:String(article?.category_id??'') });
  const mutation = useMutation({ mutationFn: () => apiRequest<Row>({ url: id ? `/knowledge/articles/${id}` : '/knowledge/articles', method: id ? 'PATCH' : 'POST', data: { title: { en: form.title_en, ar: form.title_ar }, body: { en: form.body_en, ar: form.body_ar }, visibility: form.visibility, knowledge_category_id:form.knowledge_category_id||null }, headers: { 'Idempotency-Key': crypto.randomUUID() } }), onSuccess: async (data) => { await queryClient.invalidateQueries({ queryKey: ['knowledge'] }); toast.notify(id ? 'Article updated' : 'Article created'); navigate(`/knowledge/${identifier(data) || id}`); } });
  const field = (key: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [key]: e.target.value }));
  return <Card className="p-6"><form className="grid gap-5" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}><FormErrorSummary errors={(mutation.error as FormError)?.fieldErrors ?? {}}/><div className="grid gap-5 lg:grid-cols-2"><Field label="English title" required>{({id}) => <Input id={id} value={form.title_en} onChange={field('title_en')} required/>}</Field><Field label="Arabic title" required>{({id}) => <Input id={id} dir="rtl" value={form.title_ar} onChange={field('title_ar')} required/>}</Field><Field label="English article" required>{({id}) => <Textarea id={id} rows={12} value={form.body_en} onChange={field('body_en')} required/>}</Field><Field label="Arabic article" required>{({id}) => <Textarea id={id} dir="rtl" rows={12} value={form.body_ar} onChange={field('body_ar')} required/>}</Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Category">{({id}) => <Select id={id} value={form.knowledge_category_id} onChange={field('knowledge_category_id')}><option value="">No category</option>{categoryOptions.map((category)=><option key={identifier(category)} value={identifier(category)}>{pickBilingual(category.name as {ar?:string;en?:string}|string,'en')||String(category.code??identifier(category))}</option>)}</Select>}</Field><Field label="Visibility">{({id}) => <Select id={id} value={form.visibility} onChange={field('visibility')}><option value="internal">Internal</option><option value="public">Public</option></Select>}</Field></div><div className="flex flex-col-reverse gap-3 sm:flex-row"><Button type="button" variant="secondary" onClick={() => navigate(id ? `/knowledge/${id}` : '/knowledge')}>Cancel</Button><Button type="submit" busy={mutation.isPending}>{id ? 'Save changes' : 'Create article'}</Button></div></form></Card>;
}

export function NewKnowledgeArticlePage() { return <div><PageHeader title="New knowledge article" description="Author bilingual guidance for consistent customer support."/><ArticleForm/></div>; }
export function KnowledgeArticlePage() { const { t } = useTranslation(); const { articleId = '' } = useParams(); const query = useQuery({ queryKey: ['knowledge', articleId], queryFn: () => apiRequest<Row>({ url: `/knowledge/articles/${articleId}`, method: 'GET' }) }); return <div><PageHeader title="Knowledge article" actions={<Link className="ui-button ui-button--secondary" to={`/knowledge/${articleId}/edit`}>{t('pages.knowledge.edit_article')}</Link>}/><AsyncBoundary query={query} loading={<DetailPageSkeleton/>}>{(data) => { const title = data.title as Record<string,string> | string; const body = data.body as Record<string,string> | string; const state=String(data.state??'draft'); return <div className="grid gap-5"><Card className="p-6"><h2 className="text-2xl font-bold">{typeof title === 'string' ? title : title?.en}</h2><p className="mt-5 whitespace-pre-wrap leading-7">{typeof body === 'string' ? body : body?.en}</p></Card><KnowledgeRenderedPreview articleId={articleId} state={state}/><KnowledgeLifecyclePanel articleId={articleId} state={state}/></div>; }}</AsyncBoundary></div>; }
export function EditKnowledgeArticlePage() { const { articleId = '' } = useParams(); const query = useQuery({ queryKey: ['knowledge', articleId], queryFn: () => apiRequest<Row>({ url: `/knowledge/articles/${articleId}`, method: 'GET' }) }); return <div><PageHeader title="Edit knowledge article"/><AsyncBoundary query={query} loading={<FormSkeleton/>}>{(data) => <ArticleForm article={data}/>}</AsyncBoundary></div>; }
