import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { CollectionPage } from '@/features/operations/CollectionPage';
import { apiRequest } from '@/api/http/mutator';
import { AsyncBoundary } from '@/shell/AsyncBoundary';
import { Badge, Button, Card, PageHeader } from '@/components/ui';
import { useAuth } from '@/auth/AuthProvider';
import { Link } from 'react-router-dom';
import { usePermissions } from '@/auth/usePermissions';
import { PERMISSIONS } from '@/auth/permissions';
import { httpClient } from '@/api/http/client';
import { FormErrorSummary, Dialog, Field, Input, useToast } from '@/components/ui';
import { normaliseApiError } from '@/api/http/errors';
import { ResourceField, ResourceFormDialog } from '@/features/operations/ResourceFormDialog';
import { KnowledgeCategoriesPanel } from '@/features/knowledge/KnowledgeCategoriesPanel';
import { KnowledgeListV2 } from '@/features/knowledge/KnowledgeListV2';
import { V2PortalBoundary } from '@/design-system/foundations/V2PortalBoundary';
import knowledgeStyles from '@/features/knowledge/KnowledgeV2.module.css';

export function KnowledgePage() {
  const { can } = usePermissions();
  const { t, i18n } = useTranslation();
  return <V2PortalBoundary dir={i18n.dir(i18n.language)==='rtl'?'rtl':'ltr'} lang={i18n.language==='ar'?'ar':'en'}><div className={knowledgeStyles.page}><header className={knowledgeStyles.header}><div><p className={knowledgeStyles.eyebrow}>{t('pages.knowledge.content_operations')}</p><h1 className={knowledgeStyles.title}>{t('pages.knowledge.title')}</h1><p className={knowledgeStyles.description}>{t('pages.knowledge.description')}</p></div>{can(PERMISSIONS.KNOWLEDGE_ARTICLES_CREATE)&&<Link className={knowledgeStyles.primary} to="/knowledge/new">{t('pages.knowledge.new_article')}</Link>}</header><KnowledgeListV2/>{can(PERMISSIONS.KNOWLEDGE_CATEGORIES_MANAGE) && <div className={knowledgeStyles.rule}><KnowledgeCategoriesPanel/></div>}</div></V2PortalBoundary>;
}

export function AuditLogPage() {
  const { t } = useTranslation();
  return <CollectionPage title={t('admin.operations.audit_log')} description={t('admin.operations.audit_log_description')} endpoint="/audit-logs" queryKey={['audit-logs']} columns={[{ key: 'recorded_at', label: 'Time' }, { key: 'actor_uuid', label: 'Actor' }, { key: 'action', label: 'Action' }, { key: 'target_type', label: 'Target type' }, { key: 'target_id', label: 'Target ID' }]}/>;
}

export function ReportSchedulesPage() {
  const [editing,setEditing]=useState<Record<string,unknown>|null|undefined>(undefined);
  const fields: ResourceField[] = [{key:'name',label:'Schedule name',required:true},{key:'report_key',label:'Report key',required:true},{key:'format',label:'Format',kind:'select',required:true,options:['csv','xlsx','pdf'].map(value=>({value,label:value.toUpperCase()}))},{key:'filters',label:'Report filters (JSON object)',kind:'json',required:true},{key:'frequency',label:'Frequency',kind:'select',required:true,options:['daily','weekly','monthly'].map(value=>({value,label:value}))},{key:'day_of_week',label:'Day of week (0–6)',kind:'number'},{key:'day_of_month',label:'Day of month',kind:'number'},{key:'run_at_time',label:'Run time (HH:MM)',required:true},{key:'timezone',label:'Timezone',required:true},{key:'recipients',label:'Recipients (comma separated)',kind:'csv',required:true},{key:'is_active',label:'Active',kind:'checkbox'}];
  return <><CollectionPage title="Report schedules" description="Create and maintain recurring report deliveries." endpoint="/report-schedules" queryKey={['report-schedules']} columns={[{ key: 'name', label: 'Schedule' }, { key: 'report_key', label: 'Report' }, { key: 'frequency', label: 'Frequency' }, { key: 'next_run_at', label: 'Next run' }, { key: 'is_active', label: 'State' }]} actions={<Button onClick={()=>setEditing(null)}>New schedule</Button>} rowActions={(row)=><Button variant="secondary" onClick={()=>setEditing(row)}>Edit</Button>} deleteEndpoint={(row)=>`/report-schedules/${String(row.uuid ?? row.id)}`}/><ResourceFormDialog open={editing!==undefined} title={editing?'Edit report schedule':'New report schedule'} endpoint={editing?`/report-schedules/${String(editing.uuid ?? editing.id)}`:'/report-schedules'} method={editing?'PUT':'POST'} queryKey={['report-schedules']} fields={fields} initial={editing??{format:'csv',filters:{},frequency:'daily',run_at_time:'09:00',timezone:'Africa/Cairo',recipients:[],is_active:true}} onClose={()=>setEditing(undefined)}/></>;
}

export function IntegrationsPage() {
  const [section, setSection] = useState<'tokens' | 'webhooks' | 'deliveries' | 'imports'>('tokens');
  const [editing,setEditing]=useState<Record<string,unknown>|null|undefined>(undefined); const [detail,setDetail]=useState<Record<string,unknown>|null>(null); const [issuedToken,setIssuedToken]=useState(''); const { can }=usePermissions(); const { notify }=useToast(); const { t }=useTranslation();
  const config = {
    tokens: { title: t('admin.operations.api_tokens'), description: t('admin.operations.api_tokens_description'), endpoint: '/integration/tokens', columns: [{ key: 'name', label: 'Token' }, { key: 'scopes', label: 'Scopes' }, { key: 'last_used_at', label: 'Last used' }] },
    webhooks: { title: t('admin.operations.webhook_subscriptions'), description: t('admin.operations.webhook_subscriptions_description'), endpoint: '/webhooks/subscriptions', columns: [{ key: 'name', label: 'Subscription' }, { key: 'target_url', label: 'Destination' }, { key: 'is_active', label: 'State' }] },
    deliveries: { title: t('admin.operations.webhook_deliveries'), description: t('admin.operations.webhook_deliveries_description'), endpoint: '/webhooks/deliveries', columns: [{ key: 'event_type', label: 'Event' }, { key: 'state', label: 'State' }, { key: 'attempt_count', label: 'Attempts' }, { key: 'created_at', label: 'Created' }] },
    imports: { title: t('admin.operations.import_runs'), description: t('admin.operations.import_runs_description'), endpoint: '/import-runs', columns: [{ key: 'kind', label: 'Type' }, { key: 'state', label: 'State' }, { key: 'imported_rows', label: 'Imported' }, { key: 'failed_rows', label: 'Failed' }] },
  }[section];
  const manageable = section==='tokens'?can(PERMISSIONS.INTEGRATIONS_API_TOKENS_MANAGE):section==='webhooks'?can(PERMISSIONS.INTEGRATIONS_WEBHOOKS_MANAGE):section==='imports'?can(PERMISSIONS.INTEGRATIONS_IMPORT_MANAGE):false;
  const fields: ResourceField[] = section==='tokens'?[{key:'name',label:'Token name',required:true},{key:'scopes',label:'Scopes (comma separated)',kind:'csv',required:true,placeholder:'tickets.read, customers.read'}]:section==='webhooks'?[{key:'name',label:'Subscription name',required:true},{key:'target_url',label:'HTTPS destination',required:true},{key:'event_types',label:'Event types (comma separated)',kind:'csv',required:true},{key:'is_active',label:'Active',kind:'checkbox'}]:[{key:'kind',label:'Import kind',kind:'select',required:true,options:[{value:'customers',label:'Customers'},{value:'tickets',label:'Tickets'}]},{key:'mode',label:'Mode',kind:'select',required:true,options:[{value:'dry_run',label:'Dry run'},{value:'commit',label:'Commit'}]}];
  const rowId=(row:Record<string,unknown>)=>String(row.id??row.uuid);
  const createLabel=section==='tokens'?'Issue token':section==='webhooks'?'New webhook':section==='imports'?'Start import':'';
  return <div><div className="mb-5 flex flex-wrap gap-2" role="tablist" aria-label="Integration areas">{(['tokens', 'webhooks', 'deliveries', 'imports'] as const).map((item) => <Button key={item} role="tab" aria-selected={section === item} variant={section === item ? 'primary' : 'secondary'} onClick={() => {setSection(item);setEditing(undefined);}}>{item.charAt(0).toUpperCase() + item.slice(1)}</Button>)}</div><CollectionPage key={section} {...config} queryKey={['integrations', section]} actions={manageable?<Button onClick={()=>setEditing(null)}>{createLabel}</Button>:undefined} rowActions={(row)=><>{section==='webhooks'&&manageable&&<Button variant="secondary" onClick={()=>setEditing(row)}>Edit</Button>}{(section==='deliveries'||section==='imports')&&<Button variant="secondary" onClick={()=>setDetail(row)}>View details</Button>}</>} deleteEndpoint={manageable&&(section==='tokens'||section==='webhooks')?(row)=>section==='tokens'?`/integration/tokens/${rowId(row)}`:`/webhooks/subscriptions/${rowId(row)}`:undefined}/>{manageable&&section!=='deliveries'&&<ResourceFormDialog open={editing!==undefined} title={editing?`Edit ${section.slice(0,-1)}`:createLabel} endpoint={editing&&section==='webhooks'?`/webhooks/subscriptions/${rowId(editing)}`:section==='tokens'?'/integration/tokens':section==='webhooks'?'/webhooks/subscriptions':'/import-runs'} method={editing?'PUT':'POST'} queryKey={['integrations',section]} fields={fields} initial={editing??(section==='webhooks'?{is_active:true}:section==='imports'?{mode:'dry_run'}:{})} onSaved={(data)=>{if(section==='tokens'){const token=(data as {token?:string})?.token;if(token)setIssuedToken(token);}}} onClose={()=>setEditing(undefined)}/>}<Dialog open={Boolean(issuedToken)} title="API token issued" description="Copy this credential now. It will not be shown again." onClose={()=>setIssuedToken('')} footer={<Button onClick={()=>{void navigator.clipboard.writeText(issuedToken);notify('Token copied.');}}>Copy token</Button>}><Input aria-label="Issued API token" readOnly value={issuedToken}/></Dialog><Dialog open={Boolean(detail)} title="Integration details" onClose={()=>setDetail(null)} footer={<Button variant="secondary" onClick={()=>setDetail(null)}>Close</Button>}><dl className="grid gap-3">{Object.entries(detail??{}).map(([key,value])=><div key={key}><dt className="text-xs font-semibold uppercase text-slate-500">{key.replace(/_/g,' ')}</dt><dd className="mt-1 break-words text-sm">{typeof value==='object'?JSON.stringify(value):String(value??'—')}</dd></div>)}</dl></Dialog></div>;
}

export function AiOperationsPage() {
  const [section, setSection] = useState<'suggestions' | 'usage'>('suggestions');
  const { can }=usePermissions(); const client=useQueryClient(); const { notify }=useToast(); const { t }=useTranslation(); const resolve=async(row:Record<string,unknown>,decision:'accept'|'discard')=>{try{await apiRequest({url:`/ai/suggestions/${String(row.uuid??row.id)}/resolve/${decision}`,method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()}});await client.invalidateQueries({queryKey:['ai','suggestions']});notify(`Suggestion ${decision==='accept'?'accepted':'discarded'}.`);}catch{notify('The suggestion could not be resolved.','danger');}};
  return <div><div className="mb-5 flex gap-2" role="tablist" aria-label={t('admin.operations.ai_suggestions')}><Button role="tab" aria-selected={section === 'suggestions'} variant={section === 'suggestions' ? 'primary' : 'secondary'} onClick={() => setSection('suggestions')}>{t('admin.operations.ai_suggestions')}</Button><Button role="tab" aria-selected={section === 'usage'} variant={section === 'usage' ? 'primary' : 'secondary'} onClick={() => setSection('usage')}>{t('admin.operations.ai_usage')}</Button></div>{section === 'suggestions' ? <CollectionPage title={t('admin.operations.ai_suggestions')} description={t('admin.operations.ai_suggestions_description')} endpoint="/ai/suggestions" queryKey={['ai', 'suggestions']} columns={[{ key: 'type', label: 'Type' }, { key: 'state', label: 'State' }, { key: 'confidence', label: 'Confidence' }, { key: 'created_at', label: 'Created' }]} rowActions={can(PERMISSIONS.AI_SUGGESTIONS_RESOLVE)?(row)=>String(row.state)==='pending'?<><Button onClick={()=>void resolve(row,'accept')}>Accept</Button><Button variant="danger" onClick={()=>void resolve(row,'discard')}>Discard</Button></>:undefined:undefined}/> : <CollectionPage title={t('admin.operations.ai_usage')} description={t('admin.operations.ai_usage_description')} endpoint="/ai/usage" queryKey={['ai','usage']} columns={[{ key: 'feature', label: 'Feature' }, { key: 'outcome', label: 'Outcome' }, { key: 'tokens', label: 'Tokens' }, { key: 'cost_micros', label: 'Cost' }, { key: 'created_at', label: 'Created' }]}/>}</div>;
}

interface RetentionClass { days: number | null; cutoff: string | null }
interface Retention { classes: Record<string, RetentionClass>; audit_minimum_days: number }
export function DataProtectionPage() {
  const { t, i18n } = useTranslation();
  const query = useQuery({ queryKey: ['data-protection', 'retention'], queryFn: () => apiRequest<Retention>({ url: '/data-protection/retention', method: 'GET' }) });
  return <div><PageHeader title={t('admin.operations.data_protection')} description={t('admin.operations.data_protection_description')}/><AsyncBoundary query={query}>{(data) => <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(data.classes).map(([key, value]) => <Card key={key} className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t(`admin.operations.retention.${key}`, { defaultValue: key.replace(/_/g, ' ') })}</p><p className="mt-2 text-2xl font-bold tabular-nums">{value.days === null ? t('admin.operations.retention.indefinite') : t('admin.operations.retention.days', { count: value.days })}</p><p className="mt-1 text-xs text-slate-500">{value.cutoff ? t('admin.operations.retention.current_cutoff', { date: new Intl.DateTimeFormat(i18n.language, { dateStyle: 'medium' }).format(new Date(value.cutoff)) }) : t('admin.operations.retention.no_cutoff')}</p></Card>)}</div>}</AsyncBoundary></div>;
}

export function StaffAccountPage() {
  const { user } = useAuth();
  const { notify } = useToast(); const [setup, setSetup] = useState<{qr:string;codes:string[]} | null>(null); const [code,setCode]=useState(''); const [password,setPassword]=useState(''); const [dialog,setDialog]=useState<'enable'|'disable'|null>(null); const [errors,setErrors]=useState<Record<string,string[]>>({}); const [busy,setBusy]=useState(false);
  const begin = async () => { setBusy(true); setErrors({}); try { const response = await httpClient.post('/auth/two-factor'); setSetup({qr: response.data?.data?.qr_code ?? '', codes: response.data?.meta?.recovery_codes ?? []}); setDialog('enable'); } catch(error) { const api=normaliseApiError(error); setErrors(Object.keys(api.fieldErrors).length?api.fieldErrors:{form:[api.message]}); } finally { setBusy(false); } };
  const confirm = async () => { setBusy(true); try { await apiRequest({url:'/auth/two-factor/confirm',method:'POST',data:{code}}); setDialog(null); setSetup(null); notify('Two-factor authentication enabled.'); } catch(error) { const api=normaliseApiError(error); setErrors(Object.keys(api.fieldErrors).length?api.fieldErrors:{form:[api.message]}); } finally {setBusy(false);} };
  const disable = async () => { setBusy(true); try { await apiRequest({url:'/auth/two-factor',method:'DELETE',data:{password}}); setDialog(null); setPassword(''); notify('Two-factor authentication disabled.'); } catch(error) { const api=normaliseApiError(error); setErrors(Object.keys(api.fieldErrors).length?api.fieldErrors:{form:[api.message]}); } finally {setBusy(false);} };
  return <div><PageHeader title="My account" description="Your staff identity, locale, and security status."/><div className="grid gap-5 lg:grid-cols-2"><Card className="p-6"><dl className="grid gap-6 sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Name</dt><dd className="mt-1 font-semibold">{user?.name}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Email</dt><dd className="mt-1 font-semibold">{user?.email}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Access</dt><dd className="mt-1"><Badge tone="success">{user?.permission_keys.length ?? 0} permissions</Badge></dd></div></dl></Card><Card className="p-6"><h2 className="text-lg font-semibold">Two-factor authentication</h2><p className="mt-2 text-sm text-slate-600">Use an authenticator app to add a second verification step.</p><div className="mt-5 flex flex-wrap gap-2"><Button busy={busy} onClick={() => void begin()}>Set up authenticator</Button><Button variant="danger" onClick={() => {setErrors({});setDialog('disable');}}>Disable 2FA</Button></div></Card></div><Dialog open={dialog==='enable'} title="Set up authenticator" description="Scan the QR code, save the recovery codes, then enter the six-digit code." onClose={() => setDialog(null)} footer={<><Button variant="secondary" onClick={() => setDialog(null)}>Cancel</Button><Button busy={busy} disabled={code.length!==6} onClick={() => void confirm()}>Confirm setup</Button></>}><FormErrorSummary errors={errors}/>{setup?.qr && <img className="mx-auto mb-4 max-w-full" src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(setup.qr)}`} alt="Authenticator setup QR code"/>}<p className="text-sm font-semibold">Recovery codes</p><ul className="mt-2 grid grid-cols-2 gap-1 font-mono text-sm">{setup?.codes.map((item)=><li key={item}>{item}</li>)}</ul><Field label="Authentication code" required error={errors.code?.[0]}>{({id,describedBy})=><Input id={id} aria-describedby={describedBy} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))}/>}</Field></Dialog><Dialog open={dialog==='disable'} title="Disable two-factor authentication?" description="Your account will be protected only by its password." onClose={() => setDialog(null)} footer={<><Button variant="secondary" onClick={() => setDialog(null)}>Cancel</Button><Button variant="danger" busy={busy} onClick={() => void disable()}>Disable 2FA</Button></>}><FormErrorSummary errors={errors}/><Field label="Current password" required error={errors.password?.[0]}>{({id,describedBy})=><Input id={id} aria-describedby={describedBy} type="password" autoComplete="current-password" value={password} onChange={(e)=>setPassword(e.target.value)}/>}</Field></Dialog></div>;
}
