import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useMutation, useQuery } from '@tanstack/react-query';
import type { UseQueryResult } from '@tanstack/react-query';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { apiRequest } from '@/api/http/mutator';
import { ApiPage } from '@/api/http/envelope';
import { AsyncBoundary } from '@/shell/AsyncBoundary';
import { Button, Card, Field, FormErrorSummary, Input, PageHeader, Select, Textarea } from '@/components/ui';
import { useGetPublicChatDepartments } from '@/api/generated/channels/channels';

type Localised = string | Record<string, string>;
const text = (value: Localised | undefined) => typeof value === 'string' ? value : value?.[localStorage.getItem('locale') ?? 'en'] ?? value?.en ?? value?.ar ?? '';
interface PublicField { id: string; key: string; label: Localised; type: string; is_required: boolean; options?: Array<string | { value: string; label?: Localised }> }
interface PublicForm { id: string; key: string; title: Localised; description?: Localised; fields: PublicField[] }
interface Acknowledgement { ticket_reference: string; tracking_token: string; was_duplicate: boolean }

function PublicFrame({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-2xl"><Link to="/portal/help" className="mb-6 inline-flex font-semibold text-blue-700">Support center</Link>{children}</div></main>; }

export function PublicWebFormPage() {
  const { t } = useTranslation();
  const { formKey = '' } = useParams(); const [answers, setAnswers] = useState<Record<string,string>>({});
  const query = useQuery({ queryKey: ['public-form', formKey], queryFn: () => apiRequest<PublicForm>({ url: `/channels/public/web-forms/${formKey}`, method: 'GET' }) });
  const mutation = useMutation({ mutationFn: () => apiRequest<Acknowledgement>({ url: `/channels/public/web-forms/${formKey}/submissions`, method: 'POST', data: { answers }, headers: { 'Idempotency-Key': crypto.randomUUID() } }) });
  if (mutation.data) return <PublicFrame><Card className="p-8 text-center"><h1 className="text-2xl font-bold">Request received</h1><p className="mt-3">Reference <strong>{mutation.data.ticket_reference}</strong></p><p className="mt-2 text-slate-600">Save this private tracking link to check progress.</p><Link className="ui-button ui-button--primary mt-6" to={`/forms/submissions/${mutation.data.tracking_token}`}>{t('pages.public.track_request')}</Link></Card></PublicFrame>;
  return <PublicFrame><AsyncBoundary query={query}>{(form) => <><PageHeader title={text(form.title)} description={text(form.description)}/><Card className="p-6"><form className="grid gap-5" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}><FormErrorSummary errors={(mutation.error as {fieldErrors?: Record<string,string[]>})?.fieldErrors ?? {}}/>{form.fields.map((item) => <Field key={item.id} label={text(item.label)} required={item.is_required}>{({id}) => item.type === 'textarea' ? <Textarea id={id} required={item.is_required} value={answers[item.key] ?? ''} onChange={(e) => setAnswers((a) => ({...a,[item.key]:e.target.value}))}/> : item.type === 'select' ? <Select id={id} required={item.is_required} value={answers[item.key] ?? ''} onChange={(e) => setAnswers((a) => ({...a,[item.key]:e.target.value}))}><option value="">Select</option>{(item.options ?? []).map((option) => { const value = typeof option === 'string' ? option : option.value; return <option key={value} value={value}>{typeof option === 'string' ? option : text(option.label) || value}</option>; })}</Select> : <Input id={id} type={item.type === 'email' ? 'email' : 'text'} required={item.is_required} value={answers[item.key] ?? ''} onChange={(e) => setAnswers((a) => ({...a,[item.key]:e.target.value}))}/>}</Field>)}<Button type="submit" busy={mutation.isPending}>Submit request</Button></form></Card></>}</AsyncBoundary></PublicFrame>;
}

export function PublicSubmissionStatusPage() { const { trackingToken = '' } = useParams(); const query = useQuery({ queryKey: ['public-form-status', trackingToken], queryFn: () => apiRequest<Record<string,unknown>>({ url: `/channels/public/web-forms/submissions/${trackingToken}`, method: 'GET' }) }); return <PublicFrame><PageHeader title="Request status"/><AsyncBoundary query={query}>{(data) => <Card className="p-6"><dl className="grid gap-5 sm:grid-cols-2">{Object.entries(data).map(([key,value]) => <div key={key}><dt className="text-xs font-semibold uppercase text-slate-500">{key.replace(/_/g,' ')}</dt><dd className="mt-1 font-semibold">{String(value ?? '—')}</dd></div>)}</dl></Card>}</AsyncBoundary></PublicFrame>; }

interface ChatStart { session_uuid: string; visitor_token: string; availability: string; queue_position?: number }
interface ChatMessage { id?: string; body?: string; author_type?: string; sent_at?: string }
interface PublicDepartment { id: string; name: Localised }
export function PublicChatPage() {
  const [params] = useSearchParams(); const [department,setDepartment]=useState(params.get('department') ?? ''); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [body,setBody]=useState(''); const [session,setSession]=useState<ChatStart|null>(() => { try { return JSON.parse(sessionStorage.getItem('support-chat') ?? 'null'); } catch { return null; } });
  const departments = useGetPublicChatDepartments({query:{enabled:!session}}) as unknown as UseQueryResult<PublicDepartment[],unknown>;
  const messages = useQuery({ queryKey:['public-chat',session?.session_uuid], queryFn:() => apiRequest<ApiPage<ChatMessage>>({url:`/channels/public/chat/sessions/${session?.session_uuid}/messages`,method:'GET',params:{visitor_token:session?.visitor_token,per_page:100}}), enabled:Boolean(session), refetchInterval:5000 });
  const start = useMutation({mutationFn:() => apiRequest<ChatStart>({url:'/channels/chat/sessions',method:'POST',data:{department,display_name:name,email,locale:localStorage.getItem('locale')??'en'},headers:{'Idempotency-Key':crypto.randomUUID()}}),onSuccess:(data)=>{setSession(data);sessionStorage.setItem('support-chat',JSON.stringify(data));}});
  const send = useMutation({mutationFn:() => apiRequest<ChatMessage>({url:`/channels/public/chat/sessions/${session?.session_uuid}/messages`,method:'POST',data:{visitor_token:session?.visitor_token,body,client_message_id:crypto.randomUUID()},headers:{'Idempotency-Key':crypto.randomUUID()}}),onSuccess:()=>{setBody('');messages.refetch();}});
  return <PublicFrame><PageHeader title="Live support" description="Choose the team best suited to help with your request."/><Card className="p-6">{!session ? <form className="grid gap-5" onSubmit={(e)=>{e.preventDefault();start.mutate();}}><FormErrorSummary errors={(start.error as {fieldErrors?:Record<string,string[]>})?.fieldErrors ?? {}}/><Field label="Support team" required>{({id})=><Select id={id} value={department} onChange={(e)=>setDepartment(e.target.value)} required disabled={departments.isPending}><option value="">{departments.isPending ? 'Loading teams…' : 'Select a support team'}</option>{(departments.data ?? []).map((item)=><option key={item.id} value={item.id}>{text(item.name)}</option>)}</Select>}</Field>{departments.isError && <p className="ui-alert ui-alert--danger">Support teams could not be loaded. Please retry.</p>}<Field label="Name">{({id})=><Input id={id} value={name} onChange={(e)=>setName(e.target.value)}/>}</Field><Field label="Email">{({id})=><Input id={id} type="email" value={email} onChange={(e)=>setEmail(e.target.value)}/>}</Field><Button type="submit" busy={start.isPending} disabled={!department}>Start chat</Button></form> : <div><p className="mb-4 text-sm text-slate-600">Status: {session.availability}{session.queue_position ? ` · Queue position ${session.queue_position}` : ''}</p><div className="mb-5 max-h-96 space-y-3 overflow-y-auto" aria-live="polite">{(messages.data?.items ?? []).map((message,index)=><div key={message.id ?? index} className={`rounded-xl p-3 ${message.author_type==='visitor'?'ms-8 bg-blue-50':'me-8 bg-slate-100'}`}><p>{message.body}</p></div>)}</div><form className="flex gap-2" onSubmit={(e)=>{e.preventDefault();if(body.trim())send.mutate();}}><Input aria-label="Message" value={body} onChange={(e)=>setBody(e.target.value)} maxLength={4000}/><Button type="submit" busy={send.isPending}>Send</Button></form></div>}</Card></PublicFrame>;
}
